name: Terraform CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Terraform-CI:
    name: Terraform-CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
        aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
        aws-region: us-east-2